source "https://rubygems.org"

gem "awesome_print"
gem "bond"
gem "builder"
gem "byebug"
gem "edsinclair-git-pair"
gem "fancy_irb"
gem "hirb"
gem "libxml-ruby"
gem "nokogiri"
gem "paint"
gem "pivotal-tracker"
gem "pry"
gem "pt"
gem "rspec"
