source "https://rubygems.org"

gem "activesupport"
gem "awesome_print"
gem "bond"
gem "builder"
gem "byebug"
gem "edsinclair-git-pair"
gem "fancy_irb"
gem "hirb"
gem "irb"
gem "libxml-ruby"
gem "nokogiri"
gem "paint"
gem "rspec"
gem "timetrap"
