source "https://rubygems.org"

gem "activesupport"
gem "builder"
gem "edsinclair-git-pair"
gem "libxml-ruby"
gem "nokogiri"
gem "rbs"
gem "rspec"
gem "rubocop"
gem "timetrap", git: "https://github.com/edsinclair/timetrap"
